<a href="https://colab.research.google.com/github/georgiastuart/WeTeach_Python/blob/main/WeTeach_Python_Day_1_Lesson_2_Filled_out.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WeTeach_Python: Data Science in Python Prerequisits

This course is loosely based on [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook) though we will not cover everything in it (and will add some stuff also!). 

## Dealing with Data: Pandas and Numpy

We will use two large Python libraries: [Pandas](https://pandas.pydata.org/) and [NumPy](https://numpy.org/). To use them, we must **import** them:

In [ ]:
import pandas as pd
import numpy as np

**Numpy** is a math library that provides access to efficient arrays.

**Pandas** is a data analysis library.

## Numpy Arrays

Numpy arrays are similar to **lists** in Python (see lesson 1). However, Numpy arrays are more similar to arrays in C or Java: they must contain all the same type of data. 

Numpy arrays are n-dimensional (they can have as many dimensions as you'd like). However, we'll mostly stick to 1 to 3 dimensional arrays. 

In [ ]:
# This creates a 1-dimensional array filled with zeros of type integer
my_int_array = np.zeros(100, dtype='int')
my_int_array

my_int_array.size

100

### Array indexing and slicing

Numpy arrays can be **indexed** and **sliced**. The following code sets the first and last indices (index 0 and index -1) to 10 and then index 20 through 39 to 30:

In [ ]:
my_int_array[0] = 10
my_int_array[-1] = 10

my_int_array[20:40] = 30

my_int_array

array([10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10])

**Your turn!**

In the code box below, set index 65 through 89 to 8.

In [ ]:
my_int_array[65:90] = 8

my_int_array

my_int_array[65:90:2] = 50

my_int_array

array([10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 50,  8, 50,
        8, 50,  8, 50,  8, 50,  8, 50,  8, 50,  8, 50,  8, 50,  8, 50,  8,
       50,  8, 50,  8, 50,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10])

### Two dimensional arrays

Frequently we need to use two dimensional numpy arrays. They're similar to 1-D, but they have two indices to represent the row and then the column. Unlike 2-D lists (or general 2-D arrays in languages like C and Java), 2-D Numpy arrays will always have the same number of columns in each row.

Here's an example:

In [ ]:
my_2d_array = np.zeros((10, 10), dtype='int')
print(my_2d_array)
print()

# Sets row 1 column 1 to 10
my_2d_array[1, 1] = 10
print(my_2d_array)
print()

# Sets rows 2 through 6 and columns 3 through 5 to 20
my_2d_array[2:7, 3:6] = 20
print(my_2d_array)
print()

# Prints the entire row at index 3
print(my_2d_array[3, :])

# Everything after 4th row and 5th column
print(my_2d_array[3:, 4:])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0 20 20 20  0  0  0  0]
 [ 0  0  0 20 20 20  0  0  0  0]
 [ 0  0  0 20 20 20  0  0  0  0]
 [ 0  0  0 20 20 20  0  0  0  0]
 [ 0  0  0 20 20 20  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]

[ 0  0  0 20 20 20  0  0  0  0]
[[20 20  0  0  0  0]
 [20 20  0  0  0  0]
 [20 20  0  0  0  0]
 [20 20  

**Your turn!**

Print out rows 5 through 8 and columns 6 through 9.


### Manipulating Numpy Arrays

Numpy arrays (n dimensional) can be manipulated in bulk with math operations:

In [ ]:
array1 = np.random.random((10, 10))
array2 = np.random.random((10, 10))

# print(array1, array2)

array_sum = array1 + array2
array_componentwise_product = array1 * array2
array_matrix_product = array1 @ array2
array_add_2 = array1 + 2
array_times_2 = array1 * 2

# print(np.array(array_add_2, dtype='int'))

new_array = np.array(array1)
new_array[array1 < 0.5] = 50

print(new_array)
print(array1)

[[ 0.84803217 50.         50.          0.91150323  0.84062527 50.
  50.         50.          0.96432541  0.96569649]
 [ 0.56149198 50.          0.61445171  0.53317545  0.80943213  0.93896985
  50.          0.59751031  0.84696289 50.        ]
 [ 0.53464179 50.          0.91125793 50.         50.          0.92212483
  50.         50.          0.79732604  0.53572307]
 [ 0.63054933 50.          0.50369102 50.          0.71755529 50.
  50.          0.99367514 50.          0.5386112 ]
 [ 0.67922235  0.77898222 50.          0.6469775   0.68602557  0.80145247
   0.92323454  0.76864307 50.          0.65370567]
 [50.         50.          0.72626082 50.         50.         50.
  50.          0.65063549  0.89435589  0.65152988]
 [ 0.63784667  0.92666763  0.65723397  0.58265913 50.          0.64511984
   0.79103036 50.         50.         50.        ]
 [ 0.97373706 50.         50.         50.          0.66274703 50.
   0.55240988  0.93368004  0.99670195  0.58935839]
 [50.          0.7203257   0.852

### Loading Numpy Arrays from File

Numpy arrays can be stored in a variety of file formats, including:
- numpy format (.npy)
- comma separated values (csv)
- hierarchichal data format (HDF5)

Lets first load the HDF5 interface module, `h5py`:

In [ ]:
import h5py

Now, lets save a numpy array to each type of file format:

In [ ]:
my_array = np.zeros((100, 100), dtype='int')

for i in range(100):
  for j in range(100):
    my_array[i, j] = i * j

my_array

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    1,    2, ...,   97,   98,   99],
       [   0,    2,    4, ...,  194,  196,  198],
       ...,
       [   0,   97,  194, ..., 9409, 9506, 9603],
       [   0,   98,  196, ..., 9506, 9604, 9702],
       [   0,   99,  198, ..., 9603, 9702, 9801]])

In [ ]:
drive_path = '/content/drive/MyDrive/Colab Notebooks/'

In [ ]:
# Saving in numpy format (.npy)
np.save(drive_path + 'numpy_format_save.npy', my_array)

In [ ]:
# Saving in csv format
np.savetxt(drive_path + 'csv_format_save.csv', my_array, delimiter=',')

In [ ]:
# Saving in hdf5 format
# The "with" is called using a context manager in Python
with h5py.File(drive_path + 'hdf5_save_file.hdf5', 'w') as fp:
  dset = fp.create_dataset('my_array', (100, 100), dtype='int')
  dset[:, :] = my_array[:, :]
  dset[3, :] = 0

**An aside: hdf5**

HDF5 is commonly used in scientific computing because you can store multiple named matrices / arrays together. For example, this file will contain two matrices:

In [ ]:
with h5py.File(drive_path + 'hdf5_save_file_2arrays.hdf5', 'w') as fp:
  dset = fp.create_dataset('my_array', (100, 100), dtype='int')
  dset[:, :] = my_array[:, :]
  dset = fp.create_dataset('random_array', (100, 100), dtype='float64')
  dset[:, :] = np.random.random((100, 100))

### Reading Numpy Arrays in from file

Now lets read back in the arrays we just saved:

In [ ]:
# Reads from .npy format
from_npy = np.load(drive_path + 'numpy_format_save.npy')
from_npy

print((from_npy == my_array).all())

True


In [ ]:
# Reads from .csv format
from_csv = np.loadtxt(drive_path + 'csv_format_save.csv', delimiter=',')
from_csv = np.array(from_csv, dtype='int')
from_csv

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    1,    2, ...,   97,   98,   99],
       [   0,    2,    4, ...,  194,  196,  198],
       ...,
       [   0,   97,  194, ..., 9409, 9506, 9603],
       [   0,   98,  196, ..., 9506, 9604, 9702],
       [   0,   99,  198, ..., 9603, 9702, 9801]])

In [ ]:
# Reads from hdf5 format
with h5py.File(drive_path + 'hdf5_save_file_2arrays.hdf5', 'r') as fp:
  from_hdf5 = fp['my_array'][:, :]
  print(fp.keys())

from_hdf5

<KeysViewHDF5 ['my_array', 'random_array']>


array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    1,    2, ...,   97,   98,   99],
       [   0,    2,    4, ...,  194,  196,  198],
       ...,
       [   0,   97,  194, ..., 9409, 9506, 9603],
       [   0,   98,  196, ..., 9506, 9604, 9702],
       [   0,   99,  198, ..., 9603, 9702, 9801]])

**Your Turn!**

Create a 1000 x 1000 x 100 array of integers and fill it with whatever you'd like. Then, save it and load it back in with each of the two 3D filetypes above (npy and hdf5).

In [ ]:
my_3D_array = np.random.random((1000, 1000, 100))

np.save(drive_path + "3D_array.npy", my_3D_array)

In [ ]:
read_back_in_3D_array = np.load(drive_path + "3D_array.npy")

print(read_back_in_3D_array.shape)

(1000, 1000, 100)


In [ ]:
with h5py.File(drive_path + 'hdf5_save_file.hdf5', 'a') as fp:
  # dset = fp.create_dataset('large_array', my_3D_array.shape)
  dset = fp['large_array']
  dset[:, :, :] = my_3D_array[:, :, :]
  dset[:, :, 0] = 0.0

In [ ]:
with h5py.File(drive_path + 'hdf5_save_file.hdf5', 'r') as fp:
  print(fp.keys())
  first_matrix = fp['large_array'][:, :, 1]

print(first_matrix)

<KeysViewHDF5 ['large_array', 'my_array']>
[[0.8422926  0.28939086 0.43755364 ... 0.6565679  0.36288857 0.7750237 ]
 [0.524868   0.47148004 0.20626897 ... 0.7970056  0.8949179  0.31797847]
 [0.35428166 0.9890741  0.62781173 ... 0.30251363 0.41623938 0.6981619 ]
 ...
 [0.26898065 0.627039   0.82230455 ... 0.9593426  0.13117346 0.9935259 ]
 [0.36076927 0.07364127 0.83666205 ... 0.19566277 0.53470397 0.9454175 ]
 [0.11690678 0.20341316 0.12732378 ... 0.6590659  0.9665019  0.60548717]]


## Pandas Data Frames

Numpy arrays are good for data that is all one type. What if you have a collection of data (like a spreadsheet) that has multiple types of information?

We can use a Pandas data frame.

In [ ]:
cas_data = pd.read_csv('https://raw.githubusercontent.com/georgiastuart/WeTeach_Python/main/cas_data.csv', header=0, encoding = "ISO-8859-1", engine='python')
cas_data

Country           Region  ... Importance_Internet_access  Unnamed: 20
0       USA               DC  ...                      460.0          NaN
1        OZ  New South Wales  ...                      184.0          NaN
2        NZ          Waikato  ...                        NaN          NaN
3        NZ         Auckland  ...                        NaN          NaN
4        NZ         Auckland  ...                        NaN          NaN
..      ...              ...  ...                        ...          ...
495      CA           Quebec  ...                      107.0          NaN
496      NZ            Otago  ...                        NaN          NaN
497      UK       South West  ...                        0.0          NaN
498      OZ       Western OZ  ...                        NaN          NaN
499      CA          Ontario  ...                      439.0          NaN

[500 rows x 21 columns]

We can pull out specific columns from the data frame:

In [ ]:
cas_data['Height']

0      139
1      168
2      188
3      155
4      165
      ... 
495    150
496    144
497    173
498    139
499    160
Name: Height, Length: 500, dtype: int64

We can also perform statistics on the data frame:

In [ ]:
cas_data.mean(numeric_only=True)

Ageyears                          13.392000
Height                           160.378000
Foot_Length                       23.842000
Arm_Span                         157.404000
Languages_spoken                   1.538000
Travel_time_to_School             17.078000
Reaction_time                      0.420589
Score_in_memory_game              38.738000
Importance_reducing_pollution    657.486000
Importance_recycling_rubbish     631.791284
Importance_conserving_water      644.700000
Importance_saving_enery          650.827338
Importance_owning_computer       586.223529
Importance_Internet_access       640.667464
Unnamed: 20                             NaN
dtype: float64

In [ ]:
cas_data.median(numeric_only=True)

Ageyears                          13.00
Height                           160.00
Foot_Length                       24.00
Arm_Span                         158.00
Languages_spoken                   1.00
Travel_time_to_School             15.00
Reaction_time                      0.39
Score_in_memory_game              40.00
Importance_reducing_pollution    703.50
Importance_recycling_rubbish     626.00
Importance_conserving_water      669.50
Importance_saving_enery          693.00
Importance_owning_computer       604.00
Importance_Internet_access       706.00
Unnamed: 20                         NaN
dtype: float64

Or we can perform stats on a specific column:

In [ ]:
cas_data['Height'].mean()

160.378